name: TestDriver.ai / Run Linux / Explore

permissions:
  actions: read
  contents: read
  statuses: write
  pull-requests: write

on:
  pull_request:
    branches:
      - main 

jobs:
  manual:
    runs-on: ubuntu-latest
    steps:
      - uses: testdriverai/action@main
        with:
          os: linux
          key: ${{ secrets.TESTDRIVER_API_KEY }}
          prompt: 1. open the browser
          prerun: |
            exit
          create-pr: true
          version: "5.0.7"
          pr-title: "TestDriver.ai / Generate Test Plans"
          pr-branch: testdriver/generate-${{ github.run_id }}-${{ github.run_attempt }}
        env:
          FORCE_COLOR: "3"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}